# Generated by Django 5.1.2 on 2024-10-28 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='extract_data_parameters_list',
            fields=[
                ('parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('paramter_type', models.CharField(max_length=45)),
                ('parameter_name', models.CharField(max_length=45)),
                ('parameter_options', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='extract_etl_list',
            fields=[
                ('etl_id', models.AutoField(primary_key=True, serialize=False)),
                ('etl_name', models.CharField(max_length=45)),
                ('subscription_id', models.CharField(max_length=45)),
                ('etl_description', models.CharField(max_length=45)),
                ('resource_group_name', models.CharField(max_length=45)),
                ('factory_name', models.CharField(max_length=45)),
                ('pipeline_id', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='function_list',
            fields=[
                ('function_id', models.AutoField(primary_key=True, serialize=False)),
                ('function_name', models.TextField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='source_list',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.TextField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='etl_local_parameters_mapping',
            fields=[
                ('etl_local_parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extract.extract_data_parameters_list')),
                ('etl_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extract.extract_etl_list')),
            ],
        ),
        migrations.CreateModel(
            name='etl_global_parameters_mapping',
            fields=[
                ('etl_global_parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_valu', models.CharField(max_length=45)),
                ('parameter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extract.extract_data_parameters_list')),
                ('etl_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extract.extract_etl_list')),
            ],
        ),
        migrations.CreateModel(
            name='extract_subscription_list',
            fields=[
                ('last_execution_time', models.DateTimeField(auto_created=True)),
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_name', models.CharField(max_length=45)),
                ('created_by', models.CharField(max_length=45)),
                ('etl_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extract.extract_etl_list')),
            ],
        ),
        migrations.CreateModel(
            name='extract_subscription_parameters_mapping',
            fields=[
                ('subscription_parameter_id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter_value', models.CharField(max_length=45)),
                ('parameter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extract.extract_data_parameters_list')),
                ('subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extract.extract_subscription_list')),
            ],
        ),
        migrations.CreateModel(
            name='function_source_mapping',
            fields=[
                ('function_source_id', models.AutoField(primary_key=True, serialize=False)),
                ('function_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extract.function_list')),
                ('source_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extract.source_list')),
            ],
        ),
        migrations.CreateModel(
            name='function_source_etl_mapping',
            fields=[
                ('function_source_etl_id', models.AutoField(primary_key=True, serialize=False)),
                ('etl_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extract.extract_etl_list')),
                ('function_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extract.function_list')),
                ('source_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='extract.source_list')),
            ],
        ),
    ]
