# Generated by Django 5.1.2 on 2024-10-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function_list',
            name='function_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='source_list',
            name='source_name',
            field=models.CharField(max_length=45),
        ),
    ]
