# Generated by Django 5.1.2 on 2024-10-28 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0002_alter_function_list_function_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etl_global_parameters_mapping',
            old_name='etl_id',
            new_name='etl',
        ),
        migrations.RenameField(
            model_name='etl_global_parameters_mapping',
            old_name='parameter_id',
            new_name='parameter',
        ),
        migrations.RenameField(
            model_name='etl_local_parameters_mapping',
            old_name='etl_id',
            new_name='etl',
        ),
        migrations.RenameField(
            model_name='etl_local_parameters_mapping',
            old_name='parameter_id',
            new_name='parameter',
        ),
        migrations.RenameField(
            model_name='extract_subscription_list',
            old_name='etl_id',
            new_name='etl',
        ),
        migrations.RenameField(
            model_name='extract_subscription_parameters_mapping',
            old_name='parameter_id',
            new_name='parameter',
        ),
        migrations.RenameField(
            model_name='extract_subscription_parameters_mapping',
            old_name='subscription_id',
            new_name='subscription',
        ),
        migrations.RenameField(
            model_name='function_source_etl_mapping',
            old_name='etl_id',
            new_name='etl',
        ),
        migrations.RenameField(
            model_name='function_source_etl_mapping',
            old_name='function_id',
            new_name='function',
        ),
        migrations.RenameField(
            model_name='function_source_etl_mapping',
            old_name='source_id',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='function_source_mapping',
            old_name='function_id',
            new_name='function',
        ),
        migrations.RenameField(
            model_name='function_source_mapping',
            old_name='source_id',
            new_name='source',
        ),
    ]
