# Generated by Django 5.1.2 on 2024-10-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0003_rename_etl_id_etl_global_parameters_mapping_etl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etl_global_parameters_mapping',
            old_name='parameter_valu',
            new_name='parameter_value',
        ),
    ]
